### PR TITLE
Remove second slather call

### PR DESCRIPTION
**Pull request by rastersize**
The `coverage` call will also upload it.

### CODE REVIEW

**Comment by rastersize** [comment]
@jgavris @8W9aG

**Comment by 8W9aG** [comment]
:+1:

**Comment by jgavris** [comment]
:+1:

**Comment by rastersize** [comment]
:-1: for now while we investigate why the coverage wasn’t reported.

**Comment by rastersize** [comment]
Closing this in favor of #17.

**Pull request closed without merging**
