### PR TITLE
Treat warnings as errors

### PR DESCRIPTION
**Pull request by 8W9aG**
* Should only affect the open source CI

### CODE REVIEW

**Comment by 8W9aG** [comment]
@jgavris @rastersize @dflems @JensAyton

**Comment by rastersize** [comment]
Hmm, won’t that affect all builds of the project? Or will our build-system “overwrite” it?

**Comment by 8W9aG** [comment]
Our build-system should overwrite it (since it will overwrite the project.xcconfig and point it to spotify_shared.xcconfig)

**Comment by rastersize** [comment]
@8W9aG ok, :tada: :+1:

**Pull request merged**
