### PR TITLE
Separate out targets

### PR DESCRIPTION
**Pull request by 8W9aG**
* This puts the targets into separate xcodeproj's in order to prevent polluting the Spotify projects namespace

### CODE REVIEW

**Comment by 8W9aG** [comment]
@rastersize @dflems @jgavris @JensAyton

**Comment by rastersize** [comment]
Hmm, this seems to have broken Carthage:

```shell
[21:26] Temp  ➜  echo "github \"8W9aG/SPTDataLoader\" \"separate-out-targets\"" > Cartfile
[21:26] Temp  ➜  carthage update
*** Cloning SPTDataLoader
*** Checking out SPTDataLoader at "eb0d3715c573f0e7a377f14835a06afe5d471071"
*** xcodebuild output can be found in /var/folders/52/kcvl_20s7k9_cs0bc4rmr0680000gn/T/carthage-xcodebuild.5aCX4Y.log
*** Building scheme "SPTDataLoader-OSX" in SPTDataLoaderFramework.xcodeproj
Parse error: unexpected SDK key "tvsimulator"
```

**Comment by 8W9aG** [comment]
@rastersize I see it, working on it

**Comment by 8W9aG** [comment]
I've decided to do this in 2 separate parts, one that deals with the framework, the other that deals with the demo. Here is the demo: https://github.com/spotify/SPTDataLoader/pull/77

**Pull request closed without merging**
