### PR TITLE
Use incredibly strict warning set for SPTDataLoader

### PR DESCRIPTION
**Pull request by 8W9aG**
* Removes the use of spotify_shared.xcconfig
* Disables a handful of warnings, but generally uses -Weverything

### CODE REVIEW

**Comment by 8W9aG** [comment]
@rastersize @dflems @jgavris @JensAyton

**Comment by 8W9aG** [comment]
From Spotify's perspective are we just using spotify_shared for common warnings on our modules? Is there anything else that needs to be considered?

**Comment by jgavris** [comment]
:+1:

**Comment by 8W9aG** [comment]
Will merge this now, will revert if it causes troubles with our build system

**Pull request merged**
