### PR TITLE
Add Spotify FOSS slack badge to readme

### PR DESCRIPTION
**Pull request by rastersize**
@8W9aG @jgavris @dflems @econchick

### CODE REVIEW

**Comment by jgavris** [comment]
:+1:

**Comment by 8W9aG** [comment]
:+1:

**Comment by rastersize** [comment]
Also feel free to join it (Spotify employees can skip the request invite part and just login with your `@spotify.com` email). There’s a `#ios` channel as well.

**Comment by econchick** [comment]
These PRs make me so happy 😆😆

**Pull request merged**
