### PR TITLE
Added 'Contribution' section to README file

### PR DESCRIPTION
**Pull request by iOSCowboy**

### CODE REVIEW

**Comment by iOSCowboy** [comment]
Review: @8W9aG

**Comment by 8W9aG** [comment]
:+1:

**Comment by rastersize** [comment]
It would be nice if we could move/copy this to a CONTRIBUTING.md file as GitHub would then show it when people open a PR :smiley:

**Comment by iOSCowboy** [comment]
Contributions are welcomed as PRs, @rastersize. :D

Enjoying :spaghetti: in :tomato: sauce?

**Comment by rastersize** [comment]
@iOSCowboy was at an offsite skiing so was a bit hard to do any changes :wink: Will try to get some nice :pasta: from you tonight :tada:

**Pull request merged**
