### PR TITLE
Retry tests when they fail

### PR DESCRIPTION
**Pull request by 8W9aG**
* Due to some erroneous failures on CI, attempt
to rerun xcodebuild if the tests fail

### CODE REVIEW

**Comment by jgavris** [comment]
Link to failures? Spurious timeouts?

**Comment by 8W9aG** [comment]
It seems like the sim doesn't boot on some (especially on iPhone 5/S), will attempt to find some links

**Comment by 8W9aG** [comment]
https://travis-ci.org/spotify/SPTDataLoader/jobs/105940037

**Comment by jgavris** [comment]
Ah. https://github.com/travis-ci/travis-ci/issues/4725

**Comment by jgavris** [comment]
:+1:

**Pull request merged**
