### PR TITLE
Add GIFs to high level sections in README

### PR DESCRIPTION
**Pull request by 8W9aG**
* ScoreMe gives higher scores for READMEs with GIFs
so lets add couple in

### CODE REVIEW

**Comment by 8W9aG** [comment]
@rastersize @jgavris @dflems

**Comment by iOSCowboy** [comment]
:dancer:

**Comment by dflems** [comment]
this seems unnecessary. do we really care about an arbitrary readme score?

**Comment by rastersize** [comment]
I agree with @dflems here, we've already reached 100/100 points. This here seems to mostly hurt readability and as such the quality of the readme. At least that's my opinion.

**Comment by 8W9aG** [comment]
Agreed

**Pull request closed without merging**
